services:
  postgres:
    image: postgres:15
    container_name: mfo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mfo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: mfo-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
