services:
  postgres:
    image: postgres:15
    container_name: mfo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mfo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mfo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: mfo-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mfo-api
    ports:
      - "3001:3001"
      - "9229:9229"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mfo_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/packages/database/node_modules
    command: >
      sh -c "
        echo 'â³ Aguardando Banco de Dados...' &&
        
        echo 'ðŸš€ Gerando Prisma Client...' &&
        pnpm --filter @mfo/database exec prisma generate &&
        
        echo 'ðŸ”„ Sincronizando Tabelas (DB Push)...' &&
        pnpm --filter @mfo/database exec prisma db push --accept-data-loss &&
        
        echo 'ðŸ”§ Criando entrypoint index.js...' &&
        echo \"module.exports = require('@prisma/client');\" > packages/database/index.js &&
        
        echo 'ðŸŸ¢ Iniciando NestJS com Webpack...' &&
        pnpm --filter @mfo/api run start:dev
      "
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mfo-web
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/.next
    command: pnpm --filter web run dev

volumes:
  postgres_data:
